python -m vision_experiments/imagenet_run \
    --root_dir "~/data" \
    --seed 42 \
    --device "cuda" \ 
    --lora_r 16 \ 
    --lora_alpha 32 \  
    --lora_dropout 0.1 \ 
    --batch_size 256 \ 
    --learning_rate 1e-5 \
    --downstream_learning_rate 3e-3 \ 
    --num_epochs 1 \ 
    --validate_every 150 \ 
    --hessian_average_epochs 5 \
